title: Institut für Übersetzen und Dolmetschen (IÜD), Universität Heidelberg
logo: /assets/img/logo.png
description: Abteilung für Translation, Kommunikation und Technologie, Institut für Übersetzen und Dolmetschen, Universität Heidelberg, Plöck 57a, 69117 Heidelberg. Contact Professor Dr. Bogdan Babych, email bogdan.babych@iued.uni-heidelberg.de
show_downloads: false
theme: jekyll-theme-minimal
